version: "3"

services:
  server:
    depends_on:
      - "database"
    container_name: "formbuilder-server"
    entrypoint: "./.docker/entrypoint.sh"
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./app:/app/app
      - ./pages:/app/pages
      - ./src:/app/src
      - ./public:/app/public
      - ./styles:/app/styles
      - ./prisma:/app/prisma
  database:
    image: postgres:latest
    container_name: "formbuilder-database"
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
